name: Publish
on:
  push:
    branches:
      - 'main'

env:
  node_version: 20
  pnpm_version: 9

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpm_version }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Create Release Pull Request or Publish
        id: changets
        uses: changesets/action@v1
        with:
          publish: pnpm run ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
